
services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql_container
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: ems
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
